# include: package:flutter_lints/flutter.yaml
include: package:very_good_analysis/analysis_options.3.1.0.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    public_member_api_docs: false
