name: testapp
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  cached_network_image: ^3.2.3
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_slidable: ^2.0.0
  flutter_svg: ^1.1.6
  get: ^4.6.5
  intl: ^0.18.0
  json_annotation: ^4.7.0
  mocktail: ^0.3.0
  platform: ^3.1.0
  retrofit: ^3.3.1
  shared_preferences: ^0.5.5

dev_dependencies:
  build_runner: ^2.3.0
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.5.4
  retrofit_generator: ^4.2.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/recipes1.json
    - assets/recipes2.json
    - assets/images/
